Fourier drawing functionality
sfc-aqua/qleap-c2q-optics-js-app pull request #6
Opened 2021-11-27 11:23 UTC by martian17

Implemented the fourier transform function, and added some presets that makes use of that.

2021-11-27 12:02 UTC, zigen requested changes
it works on my machine, and it's so nice! almost LGTM.
just I left several nitpicks, could you check and consider fixing it?

2021-11-27 12:02 UTC, zigen commented on src/pages/FourierAnalysis/constants.js
> +    /*return {
if you don't need this, could you remove it?

2021-11-27 12:02 UTC, zigen commented on src/pages/FourierAnalysis/constants.js
> +    const width = 1500;
hmm, we should need to handle the "resize" event later.

2021-11-27 12:02 UTC, zigen commented on src/pages/FourierAnalysis/constants.js
> +    const canvas = document.createElement("canvas");
it's obviously deviated from the React way. let's refactor this later (in another PR)

2021-11-27 12:02 UTC, zigen commented on src/pages/FourierAnalysis/constants.js
> +    //document.body.appendChild(canvas);
if you don't need this, don't comment out. just delete it. please...

2021-11-27 12:02 UTC, zigen commented on src/pages/FourierAnalysis/waveForm.js
> +    console.log(harmonics);
remove all `console.log` for debug purposes. basically, we don't need it.

2021-11-28 08:14 UTC, martian17 commented on src/pages/FourierAnalysis/constants.js
> +    const width = 1500;
oh actually this has nothing to do with resizing, I'm creating a height map by drawing letters to a temp canvas.
The canvas will be created and destroyed in an instant, and will never be displayed.

2021-11-28 08:17 UTC, martian17 commented on src/pages/FourierAnalysis/constants.js
> +    const width = 1500;
I reckon it's kind of hacky though, it's basically contained so shouldn't have any side effects.

2021-11-28 08:23 UTC, zigen commented on src/pages/FourierAnalysis/constants.js
> +    const width = 1500;
Ah, I totally understood what you want to do. why don't you separate the text image generation into another function on top of this file?

2021-11-28 08:38 UTC, zigen approved these changes
LGTM

2021-11-28 08:41 UTC, merged